# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'saiyangolf' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for saiyangolf
  # rn_path = '../node_modules/react-native'
  # pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  # pod 'React', path: rn_path, subspecs: [
  #   'ART',
  # ]

  target 'saiyangolf-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'saiyangolfTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'saiyangolf-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for saiyangolf-tvOS

  # target 'saiyangolf-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
